services:
  mysql:
    image: mysql:8.0
    container_name: banking_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: banking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql